### ISSUE TITLE
Livox Mid-70 and IMU Calibration

### ISSUE THREAD

**Issue by h-rover** [hku-mars/mlcc#11]
Hi Team,

Great work. I am struggling with the calibration of the Livox Mid-70 and IMU. Which package or process would you guys suggest to tackle this issue ? Thanks!

**Comment by samsdolphin** [comment]
Hi, for the LiDAR-IMU initialization, you may check [this](https://github.com/hku-mars/LiDAR_IMU_Init) out.

**Comment by pedestrain123** [comment]
> Hi, for the LiDAR-IMU initialization, you may check [this](https://github.com/hku-mars/LiDAR_IMU_Init) out.

你好，我想进行lidar和组合惯导rtk之间的外参标定，请问您们有相应的标定方法吗？
