### ISSUE TITLE
camera_calib std::bad_alloc

### ISSUE THREAD

**Issue by Alica-cmd** [hku-mars/mlcc#12]
16G memory
when run roslaunch mlcc calib_camera.launch
error:
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

**Comment by Charles617200** [comment]
Hello team and @Alica-cmd , I meet the same problem when running calib_camera.launch, but I couldn't find solution in Issues list.
`terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc`
 I am thankful for your advice.
