### ISSUE TITLE
Question about vpnp cost function

### ISSUE THREAD

**Issue by RoseWillow** [hku-mars/mlcc#2]
Dear author, thanks for your excellent work, but I am puzzled by the vpnp cost function, I did not understand why we need the line direction to compute the matrix V, and the physical meaning of this formula VRV.transpose
![a9dbc88dd7d6bdc163c148b62cf3a50](https://user-images.githubusercontent.com/34000284/141465597-ea92d267-1f9b-405d-9c72-3b964dde3242.png)
Look forward to your reply

**Comment by ChongjianYUAN** [comment]
> Dear author, thanks for your excellent work, but I am puzzled by the vpnp cost function, I did not understand why we need the line direction to compute the matrix V, and the physical meaning of this formula VRV.transpose ![a9dbc88dd7d6bdc163c148b62cf3a50](https://user-images.githubusercontent.com/34000284/141465597-ea92d267-1f9b-405d-9c72-3b964dde3242.png) Look forward to your reply

![微信图片_20211116131731](https://user-images.githubusercontent.com/51600805/141925312-1301b009-3301-40bd-bc63-dba53599f5aa.png)
the line direction can help us build point-to-line residual but not point-to-point residual. Besides, the correct formulation of the point-to-line residual is shown in this picture. There are some minor bugs in the code, but they don't matter much after testing.

**Comment by RoseWillow** [comment]
> > Dear author, thanks for your excellent work, but I am puzzled by the vpnp cost function, I did not understand why we need the line direction to compute the matrix V, and the physical meaning of this formula VRV.transpose ![a9dbc88dd7d6bdc163c148b62cf3a50](https://user-images.githubusercontent.com/34000284/141465597-ea92d267-1f9b-405d-9c72-3b964dde3242.png) Look forward to your reply
> 
> ![微信图片_20211116131731](https://user-images.githubusercontent.com/51600805/141925312-1301b009-3301-40bd-bc63-dba53599f5aa.png) the line direction can help us build point-to-line residual but not point-to-point residual. Besides, the correct formulation of the point-to-line residual is shown in this picture. There are some minor bugs in the code, but they don't matter much after testing.

Thank you for your reply, but I still don't know how to build point-to-line residuals. Can you tell me the source of the picture in your last reply?

**Comment by ChongjianYUAN** [comment]
> > > Dear author, thanks for your excellent work, but I am puzzled by the vpnp cost function, I did not understand why we need the line direction to compute the matrix V, and the physical meaning of this formula VRV.transpose ![a9dbc88dd7d6bdc163c148b62cf3a50](https://user-images.githubusercontent.com/34000284/141465597-ea92d267-1f9b-405d-9c72-3b964dde3242.png) Look forward to your reply
> > 
> > 
> > ![微信图片_20211116131731](https://user-images.githubusercontent.com/51600805/141925312-1301b009-3301-40bd-bc63-dba53599f5aa.png) the line direction can help us build point-to-line residual but not point-to-point residual. Besides, the correct formulation of the point-to-line residual is shown in this picture. There are some minor bugs in the code, but they don't matter much after testing.
> 
> Thank you for your reply, but I still don't know how to build point-to-line residuals. Can you tell me the source of the picture in your last reply?

Sorry, the content in this picture is written by myself, so there is no source. You can refer to the vector projection matrix, then you will know how to build point-to-line residuals.

**Comment by RoseWillow** [comment]
> > > > Dear author, thanks for your excellent work, but I am puzzled by the vpnp cost function, I did not understand why we need the line direction to compute the matrix V, and the physical meaning of this formula VRV.transpose ![a9dbc88dd7d6bdc163c148b62cf3a50](https://user-images.githubusercontent.com/34000284/141465597-ea92d267-1f9b-405d-9c72-3b964dde3242.png) Look forward to your reply
> > > 
> > > 
> > > ![微信图片_20211116131731](https://user-images.githubusercontent.com/51600805/141925312-1301b009-3301-40bd-bc63-dba53599f5aa.png) the line direction can help us build point-to-line residual but not point-to-point residual. Besides, the correct formulation of the point-to-line residual is shown in this picture. There are some minor bugs in the code, but they don't matter much after testing.
> > 
> > 
> > Thank you for your reply, but I still don't know how to build point-to-line residuals. Can you tell me the source of the picture in your last reply?
> 
> Sorry, the content in this picture is written by myself, so there is no source. You can refer to the vector projection matrix, then you will know how to build point-to-line residuals.

OK，thank you very much!
