### ISSUE TITLE
calibration of one camera and one lidar

### ISSUE THREAD

**Issue by zzkslam** [hku-mars/mlcc#3]
Thanks for your excellent work. I want to use the code to calibrate one camera and one lidar. Can you give me some advice about how to change the code?

**Comment by samsdolphin** [comment]
Hi zzkslam, for single LiDAR and single-camera extrinsic calibration, we refer you to our previous work https://github.com/hku-mars/livox_camera_calib. Thanks~

**Comment by jdtsui** [comment]
> Hi zzkslam, for single LiDAR and single-camera extrinsic calibration, we refer you to our previous work https://github.com/hku-mars/livox_camera_calib. Thanks~

Thanks for your excellent work, too. But one question here: Have you updated the new algorithm (using adaptive voxelization to extract lines) to replace the old one (using RANSAC only) in "livox_camera_calib"?

**Comment by zying0393** [comment]
> 

Same question. Looking forward to your reply!

**Comment by zying0393** [comment]
> > Hi zzkslam, for single LiDAR and single-camera extrinsic calibration, we refer you to our previous work https://github.com/hku-mars/livox_camera_calib. Thanks~
> 
> Thanks for your excellent work, too. But one question here: Have you updated the new algorithm (using adaptive voxelization to extract lines) to replace the old one (using RANSAC only) in "livox_camera_calib"?

Same question. Looking forward to your reply!

**Comment by af-doom** [comment]
> > > Hi zzkslam, for single LiDAR and single-camera extrinsic calibration, we refer you to our previous work https://github.com/hku-mars/livox_camera_calib. Thanks~
> > 
> > 
> > Thanks for your excellent work, too. But one question here: Have you updated the new algorithm (using adaptive voxelization to extract lines) to replace the old one (using RANSAC only) in "livox_camera_calib"?
> 
> Same question. Looking forward to your reply!

Have you solved this problem
