### ISSUE TITLE
problem:   extrinsic_refine.hpp:309:** void EXTRIN_OPTIMIZER::optimize(): Assertion `!std::isnan(residual2)' failed.

### ISSUE THREAD

**Issue by mingkunwxc** [hku-mars/mlcc#7]
i used the scen* from your project to test this program,i got the problem：

————————————————————————————————————————————
iteration 0
residual0: 5.352935 nan u: 0.010000 v: 2.000000 q: nan -nan nan
extrinsic_refine: ********/rrrlive_/mlcc/src/mlcc/include/extrinsic_refine.hpp:309:** void EXTRIN_OPTIMIZER::optimize(): Assertion `!std::isnan(residual2)' failed.
——————————————————————————————————————————————————
how can i fix it?

**Comment by samsdolphin** [comment]
Hi, have you tried the solution in #1 ?

**Comment by mingkunwxc** [comment]
> 
thanks for your help, I succeeded.
