### ISSUE TITLE
calibration of multi-lidar and camera

### ISSUE THREAD

**Issue by JangChangWon** [hku-mars/mlcc#9]
Thanks for your excellent work.
I want to use the code to calibrate multi lidar and two- camera for my custom robot
Can you give me some advice about how to make the .dat file such as src/mlcc/scene0/00/patch0.dat?

**Comment by samsdolphin** [comment]
Hi JangChangWon, you can check our `tobinary.cpp` file for more instructions on converting your own point cloud data from `.pcd`, `.txt`, or `.json` to `.dat` format. In our future release, we will use `.pcd` as our standard point cloud file format.

**Comment by JangChangWon** [comment]
@samsdolphin 
Thank you for answering. Your answer has been a great help. Thank u :)
